apiVersion: 1

datasources:
- name: influxdb-1
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  user: dbuser
  password: dbpassword
  database: dbname
  isDefault: true
  editable: true
  version: 1