apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: mkamei/nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          containerPort: 443
          containerPort: 22
        env:
        - name: SERVICE_IP
          valueFrom:
            configMapKeyRef:
              name: service-cm
              key: SERVICE_IP
        - name: NGINXUSER_PASS
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: NGINXUSER_PASS
        - name: INFLUXUSER_PASS
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: INFLUXUSER_PASS
        livenessProbe:
          exec:
            command: ["healthcheck.sh"]
          initialDelaySeconds: 30
        volumeMounts:
        - name: docker-volume
          mountPath: /var/run/docker.sock
        - name: cert-volume
          mountPath: /secrets
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
      - name: cert-volume
        secret:
          secretName: cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing.key
spec:
  type: LoadBalancer
  selector:
    component: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
