apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    component: phpmyadmin
spec:
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: mkamei/phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing.key
spec:
  type: LoadBalancer
  selector:
    component: phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
