apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: mkamei/phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        volumeMounts:
        - name: docker-volume
          mountPath: /var/run/docker.sock
        - name: secret-volume
          mountPath: /secrets
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
      - name: secret-volume
        secret:
          secretName: secret-data
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing.key
spec:
  type: LoadBalancer
  selector:
    component: phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 443
